-- Home Sense (Avera / Tuya) price list, 07 Oct 2026, prices in EGP (end-user).
-- Loaded for both companies. Codes are unique across the table, so each company gets its own
-- prefix: JS-HS-001-W (Jaguar) and TS-HS-001-W (Tuya Suez); -W = Wi-Fi, -Z = Zigbee.

insert into public.products (company, code, name, description, category, brand, end_user_price)
select c.company, c.prefix || v.code, v.name, v.description, v.category, v.brand, v.price
from (values ('jaguar', 'JS-'), ('tuya-suez', 'TS-')) c(company, prefix)
cross join (values
  ('HS-001-W','Smart Light Switch 1-Gang (Wi-Fi)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1365),
  ('HS-001-Z','Smart Light Switch 1-Gang (Zigbee)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1465),
  ('HS-002-W','Smart Light Switch 2-Gang (Wi-Fi)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1465),
  ('HS-002-Z','Smart Light Switch 2-Gang (Zigbee)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1565),
  ('HS-003-W','Smart Light Switch 3-Gang (Wi-Fi)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1565),
  ('HS-003-Z','Smart Light Switch 3-Gang (Zigbee)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1665),
  ('HS-004-W','Smart Light Switch 4-Gang (Wi-Fi)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1665),
  ('HS-004-Z','Smart Light Switch 4-Gang (Zigbee)','Glass panel, US/EU','Light Switches (Glass)','Home Sense',1765),
  ('HS-005-W','Concave Light Switch 1-Gang (Wi-Fi)',null,'Light Switches (Concave)','Home Sense',1546),
  ('HS-005-Z','Concave Light Switch 1-Gang (Zigbee)',null,'Light Switches (Concave)','Home Sense',1646),
  ('HS-006-W','Concave Light Switch 2-Gang (Wi-Fi)',null,'Light Switches (Concave)','Home Sense',1646),
  ('HS-006-Z','Concave Light Switch 2-Gang (Zigbee)',null,'Light Switches (Concave)','Home Sense',1746),
  ('HS-007-W','Concave Light Switch 3-Gang (Wi-Fi)',null,'Light Switches (Concave)','Home Sense',1746),
  ('HS-007-Z','Concave Light Switch 3-Gang (Zigbee)',null,'Light Switches (Concave)','Home Sense',1846),
  ('HS-008-W','Concave Light Switch 4-Gang (Wi-Fi)',null,'Light Switches (Concave)','Home Sense',1846),
  ('HS-008-Z','Concave Light Switch 4-Gang (Zigbee)',null,'Light Switches (Concave)','Home Sense',1946),
  ('HS-009-W','Metal Frame Light Switch 1-Gang (Wi-Fi)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',1910),
  ('HS-009-Z','Metal Frame Light Switch 1-Gang (Zigbee)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2010),
  ('HS-010-W','Metal Frame Light Switch 2-Gang (Wi-Fi)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2010),
  ('HS-010-Z','Metal Frame Light Switch 2-Gang (Zigbee)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2110),
  ('HS-011-W','Metal Frame Light Switch 3-Gang (Wi-Fi)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2110),
  ('HS-011-Z','Metal Frame Light Switch 3-Gang (Zigbee)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2210),
  ('HS-012-W','Metal Frame Light Switch 4-Gang (Wi-Fi)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2210),
  ('HS-012-Z','Metal Frame Light Switch 4-Gang (Zigbee)','Gold frame','Light Switches (Concave – Metal Frame)','Home Sense',2310),
  ('HS-013-W','Smart Dimmer Switch (Wi-Fi)','Max 150W LED','Special Switches','Home Sense',1800),
  ('HS-013-Z','Smart Dimmer Switch (Zigbee)','Max 150W LED','Special Switches','Home Sense',1900),
  ('HS-014-W','LCD Smart Control Switch (Light/Curtain)',null,'Special Switches','Home Sense',3400),
  ('HS-015-W','Curtain Switch 1-CH (Wi-Fi)',null,'Special Switches','Home Sense',1728),
  ('HS-015-Z','Curtain Switch 1-CH (Zigbee)',null,'Special Switches','Home Sense',1828),
  ('HS-016-W','Curtain Switch 2-CH (Wi-Fi)',null,'Special Switches','Home Sense',1910),
  ('HS-016-Z','Curtain Switch 2-CH (Zigbee)',null,'Special Switches','Home Sense',2010),
  ('HS-017-W','Smart A/C & Boiler Switch (Wi-Fi)','40A','Special Switches','Home Sense',2090),
  ('HS-017-Z','Smart A/C & Boiler Switch (Zigbee)','40A','Special Switches','Home Sense',2180),
  ('HS-018-W','Smart Thermostat Control (Wi-Fi)','3A & 16A','Special Switches','Home Sense',3800),
  ('HS-018-Z','Smart Thermostat Control (Zigbee)','3A & 16A','Special Switches','Home Sense',3900),
  ('HS-019-W','Mini Light Switch 1-Gang (Wi-Fi)',null,'Mini Modules (behind switch)','Home Sense',1200),
  ('HS-019-Z','Mini Light Switch 1-Gang (Zigbee)',null,'Mini Modules (behind switch)','Home Sense',1300),
  ('HS-020-W','Mini Light Switch 2-Gang (Wi-Fi)',null,'Mini Modules (behind switch)','Home Sense',1300),
  ('HS-020-Z','Mini Light Switch 2-Gang (Zigbee)',null,'Mini Modules (behind switch)','Home Sense',1400),
  ('HS-021-W','Mini Light Switch 3-Gang (Wi-Fi)',null,'Mini Modules (behind switch)','Home Sense',1400),
  ('HS-021-Z','Mini Light Switch 3-Gang (Zigbee)',null,'Mini Modules (behind switch)','Home Sense',1500),
  ('HS-022-W','Mini Light Switch 4-Gang (Wi-Fi)',null,'Mini Modules (behind switch)','Home Sense',1500),
  ('HS-022-Z','Mini Light Switch 4-Gang (Zigbee)',null,'Mini Modules (behind switch)','Home Sense',1600),
  ('HS-023-W','Mini Curtain/Shutter Switch 1-CH (Wi-Fi)',null,'Mini Modules (behind switch)','Home Sense',1350),
  ('HS-023-Z','Mini Curtain/Shutter Switch 1-CH (Zigbee)',null,'Mini Modules (behind switch)','Home Sense',1450),
  ('HS-024-W','Mini Curtain/Shutter Switch 2-CH (Wi-Fi)',null,'Mini Modules (behind switch)','Home Sense',1550),
  ('HS-024-Z','Mini Curtain/Shutter Switch 2-CH (Zigbee)',null,'Mini Modules (behind switch)','Home Sense',1650),
  ('HS-027-W','Smart Circuit Breaker 3P',null,'Smart Circuit Breaker (Wi-Fi)','Home Sense',5400),
  ('HS-028-W','Smart Circuit Breaker 4P',null,'Smart Circuit Breaker (Wi-Fi)','Home Sense',5700),
  ('HS-029-W','Smart Socket All-in-one 3-Gang + 2USB + 1 Socket (Wi-Fi)',null,'Sockets & Plugs','Home Sense',2800),
  ('HS-029-Z','Smart Socket All-in-one 3-Gang + 2USB + 1 Socket (Zigbee)',null,'Sockets & Plugs','Home Sense',2900),
  ('HS-030-W','Smart Socket All-in-one 3-Gang + 2USB + 2 Socket (Wi-Fi)',null,'Sockets & Plugs','Home Sense',3000),
  ('HS-030-Z','Smart Socket All-in-one 3-Gang + 2USB + 2 Socket (Zigbee)',null,'Sockets & Plugs','Home Sense',3100),
  ('HS-031-W','PC Frame Smart Socket 2-Socket (Wi-Fi)',null,'Sockets & Plugs','Home Sense',2550),
  ('HS-031-Z','PC Frame Smart Socket 2-Socket (Zigbee)',null,'Sockets & Plugs','Home Sense',2650),
  ('HS-032-W','Smart Plug Socket (Wi-Fi)','10A/13A/16A','Sockets & Plugs','Home Sense',1150),
  ('HS-032-Z','Smart Plug Socket (Zigbee)','10A/13A/16A','Sockets & Plugs','Home Sense',1250),
  ('HS-033-W','Smart Curtain Kit – Complete Track System (Wi-Fi)','Motor + track','Curtain System','Home Sense',11000),
  ('HS-033-Z','Smart Curtain Kit – Complete Track System (Zigbee)','Motor + track','Curtain System','Home Sense',11200),
  ('HS-034-W','Smart Curtain Motor with Remote (Wi-Fi)','2.0 N·m, up to 12m','Curtain System','Home Sense',4690),
  ('HS-034-Z','Smart Curtain Motor with Remote (Zigbee)','2.0 N·m, up to 12m','Curtain System','Home Sense',4890),
  ('HS-035-W','Control Panel 3.5" (Built-in Alexa)',null,'Control Panels (Wi-Fi)','Home Sense',7390),
  ('HS-036-W','Control Panel 4" (Built-in Alexa)',null,'Control Panels (Wi-Fi)','Home Sense',9999),
  ('HS-037-W','Control Panel 4" (Built-in Amplifier)','With speakers','Control Panels (Wi-Fi)','Home Sense',11290),
  ('HS-038-W','Control Panel 6" (Built-in Amplifier)',null,'Control Panels (Wi-Fi)','Home Sense',16490),
  ('HS-039-W','Control Panel 7" (Built-in Amplifier) 2-Speaker',null,'Control Panels (Wi-Fi)','Home Sense',17899),
  ('HS-040-W','Control Panel 7" (Built-in Amplifier) 8-Speaker',null,'Control Panels (Wi-Fi)','Home Sense',18990),
  ('HS-041-W','Control Panel 8" (Built-in Amplifier) 2-Speaker',null,'Control Panels (Wi-Fi)','Home Sense',19490),
  ('HS-042-W','Control Panel 8" (Built-in Amplifier) 4-Speaker',null,'Control Panels (Wi-Fi)','Home Sense',19990),
  ('HS-043-W','Control Panel 8" Pro','Built-in Alexa + IR','Control Panels (Wi-Fi)','Home Sense',21790),
  ('HS-044-W','Control Panel 10" (Built-in Alexa)',null,'Control Panels (Wi-Fi)','Home Sense',25799),
  ('HS-045-W','Control Panel 10" (Built-in Amplifier) 2-Speaker',null,'Control Panels (Wi-Fi)','Home Sense',25799),
  ('HS-046-W','Zigbee Gateway Hub 3.0 – Wireless','Up to 50 devices','Gateways, Repeaters & IR','Home Sense',2190),
  ('HS-047-W','Zigbee Gateway Hub – Wired (model 1, white)','Up to 100 devices','Gateways, Repeaters & IR','Home Sense',3650),
  ('HS-048-W','Zigbee Gateway Hub – Wired (model 2, gold)','Up to 100 devices','Gateways, Repeaters & IR','Home Sense',4000),
  ('HS-049-W','Zigbee Gateway Hub – Wired (Apple HomeKit)',null,'Gateways, Repeaters & IR','Home Sense',3450),
  ('HS-050-Z','Zigbee Powerful Repeater',null,'Gateways, Repeaters & IR','Home Sense',1370),
  ('HS-051-W','Smart IR Remote with Temp & Humidity Sensor','Screen','Gateways, Repeaters & IR','Home Sense',2000),
  ('HS-052-W','Smart Wi-Fi IR Remote Control',null,'Gateways, Repeaters & IR','Home Sense',1640),
  ('HS-053-W','Smart Wi-Fi IR + RF Remote Control',null,'Gateways, Repeaters & IR','Home Sense',1910),
  ('HS-054-Z','Smart Zigbee IR Remote Control',null,'Gateways, Repeaters & IR','Home Sense',1910),
  ('HS-055-W','Human Presence Detector (ceiling, AC 80-220V) (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',2370),
  ('HS-055-Z','Human Presence Detector (ceiling, AC 80-220V) (Zigbee)',null,'Safety & Security Sensors','Home Sense',2370),
  ('HS-056-W','Human Presence Detector (DC 5V) (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',2280),
  ('HS-056-Z','Human Presence Detector (DC 5V) (Zigbee)',null,'Safety & Security Sensors','Home Sense',2280),
  ('HS-057-Z','Zigbee PIR Motion Sensor',null,'Safety & Security Sensors','Home Sense',1365),
  ('HS-058-W','Wi-Fi PIR Motion Sensor',null,'Safety & Security Sensors','Home Sense',1365),
  ('HS-059-W','Smart Gas & Temp. Detector','LCD screen','Safety & Security Sensors','Home Sense',2100),
  ('HS-060-W','Smart Gas Detector',null,'Safety & Security Sensors','Home Sense',2000),
  ('HS-061-Z','Smart Zigbee Gas Detector','Plug-in','Safety & Security Sensors','Home Sense',2000),
  ('HS-062-W','Smart Water Leak Sensor (model 1 – round) (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',1365),
  ('HS-062-Z','Smart Water Leak Sensor (model 1 – round) (Zigbee)',null,'Safety & Security Sensors','Home Sense',1465),
  ('HS-063-W','Smart Water Leak Sensor (model 2 – with probe) (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',1180),
  ('HS-063-Z','Smart Water Leak Sensor (model 2 – with probe) (Zigbee)',null,'Safety & Security Sensors','Home Sense',1280),
  ('HS-064-W','Smart Gas / Water Valve Controller (Wi-Fi)','1.25 inch','Safety & Security Sensors','Home Sense',2545),
  ('HS-064-Z','Smart Gas / Water Valve Controller (Zigbee)','1.25 inch','Safety & Security Sensors','Home Sense',2645),
  ('HS-065-W','Smart Smoke Detector (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',1800),
  ('HS-065-Z','Smart Smoke Detector (Zigbee)',null,'Safety & Security Sensors','Home Sense',1900),
  ('HS-066-W','Smart Door & Window Sensor (model 1) (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',1000),
  ('HS-066-Z','Smart Door & Window Sensor (model 1) (Zigbee)',null,'Safety & Security Sensors','Home Sense',1100),
  ('HS-067-W','Smart Door & Window Sensor (model 2) (Wi-Fi)',null,'Safety & Security Sensors','Home Sense',1200),
  ('HS-067-Z','Smart Door & Window Sensor (model 2) (Zigbee)',null,'Safety & Security Sensors','Home Sense',1300),
  ('HS-068-W','Smart Video Doorbell (silver)','1080P','Video Doorbells (Wi-Fi)','Home Sense',3935),
  ('HS-069-W','Waterproof Smart Video Doorbell IP65 (black)',null,'Video Doorbells (Wi-Fi)','Home Sense',3935),
  ('HS-070-W','Waterproof Smart Video Doorbell IP65 (black/white)',null,'Video Doorbells (Wi-Fi)','Home Sense',3935),
  ('HS-071-W','Smart Video Doorbell (black square)',null,'Video Doorbells (Wi-Fi)','Home Sense',3665),
  ('HS-072-W','Waterproof Smart Video Doorbell IP66',null,'Video Doorbells (Wi-Fi)','Home Sense',3665),
  ('HS-073-W','Smart Video Doorbell (black/white pair)',null,'Video Doorbells (Wi-Fi)','Home Sense',3799),
  ('HS-074-W','Smart Video Doorbell Intercom – LCD Door Phone','4.3" screen','Video Doorbells (Wi-Fi)','Home Sense',4665),
  ('HS-075-W','Smart Video Doorbell Intercom – HD Door Phone','4.3" HD screen','Video Doorbells (Wi-Fi)','Home Sense',6399),
  ('HS-076-W','Smart Door Lock LWF1','Face + Palm vein, Zinc','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',20950),
  ('HS-077-W','Smart Door Lock LWF2','Face + Palm vein, Zinc','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',20950),
  ('HS-078-W','Smart Door Lock LWF7','Zinc alloy','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',19455),
  ('HS-079-W','Smart Door Lock LWF9','Aluminum','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',19105),
  ('HS-080-W','Smart Door Lock LWF13','Black/Gold','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',17910),
  ('HS-081-W','Smart Door Lock LWF14','Black','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',17910),
  ('HS-082-W','Smart Door Lock LWF15','Black/Brown','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',17910),
  ('HS-083-W','Smart Door Lock LWF17','Black/Silver','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',17910),
  ('HS-084-W','Smart Door Lock LWF27','Black/Silver','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',16910),
  ('HS-085-W','Smart Door Lock LWF30','IP66 Waterproof','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18455),
  ('HS-086-W','Smart Door Lock LWF31','Black','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18455),
  ('HS-087-W','Smart Door Lock LWF33','Grey','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18190),
  ('HS-088-W','Smart Door Lock LWF34','Red brown','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',22365),
  ('HS-089-W','Smart Door Lock LWF35','Grey','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18190),
  ('HS-090-W','Smart Door Lock LWF36','Grey','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18190),
  ('HS-091-W','Smart Door Lock LWF37','Grey','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18190),
  ('HS-092-W','Smart Door Lock LWF38','Grey','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18190),
  ('HS-093-W','Smart Door Lock LWF39','Grey','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',18190),
  ('HS-094-W','Smart Door Lock LWF19','Video intercom (doorbell-triggered)','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',16910),
  ('HS-095-W','Smart Door Lock LWF22','Video intercom (doorbell-triggered)','Smart Door Locks – Fully Automatic (Wi-Fi)','Home Sense',13450),
  ('HS-096-W','Smart Door Lock LWE6','Peephole + indoor screen, video intercom','Smart Door Locks – Semi Automatic (Wi-Fi)','Home Sense',7450),
  ('HS-097-W','Smart Door Lock LWE9-PRO','Cat eye / normal version','Smart Door Locks – Semi Automatic (Wi-Fi)','Home Sense',6995),
  ('HS-098-W','Smart Door Lock LWB26','Basic version','Smart Door Locks – Semi Automatic (Wi-Fi)','Home Sense',6595)
) v(code, name, description, category, brand, price)
on conflict (code) where code is not null do update
  set name = excluded.name, description = excluded.description, category = excluded.category,
      brand = excluded.brand, end_user_price = excluded.end_user_price, active = true;
