-- Arabic names, photos and CRM categories for the Home Sense products (both companies).
alter table public.products add column if not exists name_ar text;
alter table public.products add column if not exists image_url text;

update public.products p set name_ar = v.name_ar, category = v.category, image_url = v.image_url, brand = 'Tuya'
from (values
  ('HS-001-W','مفتاح ذكي زجاج 1 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-001-Z','مفتاح ذكي زجاج 1 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-002-W','مفتاح ذكي زجاج 2 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-002-Z','مفتاح ذكي زجاج 2 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-003-W','مفتاح ذكي زجاج 3 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-003-Z','مفتاح ذكي زجاج 3 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-004-W','مفتاح ذكي زجاج 4 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-004-Z','مفتاح ذكي زجاج 4 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-1.webp'),
  ('HS-005-W','مفتاح كونكيف 1 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-005-Z','مفتاح كونكيف 1 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-006-W','مفتاح كونكيف 2 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-006-Z','مفتاح كونكيف 2 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-007-W','مفتاح كونكيف 3 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-007-Z','مفتاح كونكيف 3 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-008-W','مفتاح كونكيف 4 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-008-Z','مفتاح كونكيف 4 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-009-W','مفتاح بإطار معدن دهبي 1 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-009-Z','مفتاح بإطار معدن دهبي 1 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-010-W','مفتاح بإطار معدن دهبي 2 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-010-Z','مفتاح بإطار معدن دهبي 2 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-011-W','مفتاح بإطار معدن دهبي 3 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-011-Z','مفتاح بإطار معدن دهبي 3 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-012-W','مفتاح بإطار معدن دهبي 4 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-012-Z','مفتاح بإطار معدن دهبي 4 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-2.webp'),
  ('HS-013-W','مفتاح ديمر ذكي (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-013-Z','مفتاح ديمر ذكي (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-014-W','مفتاح تحكم بشاشة LCD (إضاءة/ستاير)','Screens & Hubs','/img/catalog/switch-life.webp'),
  ('HS-015-W','مفتاح ستارة 1 قناة (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-015-Z','مفتاح ستارة 1 قناة (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-016-W','مفتاح ستارة 2 قناة (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-016-Z','مفتاح ستارة 2 قناة (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-017-W','مفتاح تكييف وسخان 40A (واي فاي)','Switches & Sockets','/img/catalog/thermostat-2.webp'),
  ('HS-017-Z','مفتاح تكييف وسخان 40A (زيجبي)','Switches & Sockets','/img/catalog/thermostat-2.webp'),
  ('HS-018-W','ثرموستات ذكي (واي فاي)','Screens & Hubs','/img/catalog/thermostat-2.webp'),
  ('HS-018-Z','ثرموستات ذكي (زيجبي)','Screens & Hubs','/img/catalog/thermostat-2.webp'),
  ('HS-019-W','ميني موديول إضاءة 1 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-019-Z','ميني موديول إضاءة 1 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-020-W','ميني موديول إضاءة 2 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-020-Z','ميني موديول إضاءة 2 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-021-W','ميني موديول إضاءة 3 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-021-Z','ميني موديول إضاءة 3 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-022-W','ميني موديول إضاءة 4 خط (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-022-Z','ميني موديول إضاءة 4 خط (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-023-W','ميني موديول ستارة/شيش 1 قناة (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-023-Z','ميني موديول ستارة/شيش 1 قناة (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-024-W','ميني موديول ستارة/شيش 2 قناة (واي فاي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-024-Z','ميني موديول ستارة/شيش 2 قناة (زيجبي)','Switches & Sockets','/img/catalog/switch-life.webp'),
  ('HS-027-W','قاطع كهرباء ذكي 3P','Electrical','/img/catalog/breaker-life.webp'),
  ('HS-028-W','قاطع كهرباء ذكي 4P','Electrical','/img/catalog/breaker-life.webp'),
  ('HS-029-W','بريزة ذكية متكاملة 3 خط + 2 USB + بريزة (واي فاي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-029-Z','بريزة ذكية متكاملة 3 خط + 2 USB + بريزة (زيجبي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-030-W','بريزة ذكية متكاملة 3 خط + 2 USB + 2 بريزة (واي فاي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-030-Z','بريزة ذكية متكاملة 3 خط + 2 USB + 2 بريزة (زيجبي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-031-W','بريزة ذكية مزدوجة بإطار PC (واي فاي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-031-Z','بريزة ذكية مزدوجة بإطار PC (زيجبي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-032-W','فيشة ذكية (واي فاي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-032-Z','فيشة ذكية (زيجبي)','Switches & Sockets','/img/catalog/socket-1.webp'),
  ('HS-033-W','طقم ستارة ذكية كامل (موتور + تراك) (واي فاي)','Curtains','/img/catalog/curtain-kit.webp'),
  ('HS-033-Z','طقم ستارة ذكية كامل (موتور + تراك) (زيجبي)','Curtains','/img/catalog/curtain-kit.webp'),
  ('HS-034-W','موتور ستارة ذكي بريموت (واي فاي)','Curtains','/img/catalog/curtain-motor.webp'),
  ('HS-034-Z','موتور ستارة ذكي بريموت (زيجبي)','Curtains','/img/catalog/curtain-motor.webp'),
  ('HS-035-W','شاشة تحكم 3.5 بوصة (Alexa مدمجة)','Screens & Hubs','/img/catalog/panel-2.webp'),
  ('HS-036-W','شاشة تحكم 4 بوصة (Alexa مدمجة)','Screens & Hubs','/img/catalog/panel-2.webp'),
  ('HS-037-W','شاشة تحكم 4 بوصة (أمبليفاير وسماعات)','Screens & Hubs','/img/catalog/panel-2.webp'),
  ('HS-038-W','شاشة تحكم 6 بوصة (أمبليفاير)','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-039-W','شاشة تحكم 7 بوصة (أمبليفاير) 2 سماعة','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-040-W','شاشة تحكم 7 بوصة (أمبليفاير) 8 سماعات','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-041-W','شاشة تحكم 8 بوصة (أمبليفاير) 2 سماعة','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-042-W','شاشة تحكم 8 بوصة (أمبليفاير) 4 سماعات','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-043-W','شاشة تحكم 8 بوصة Pro (Alexa + IR)','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-044-W','شاشة تحكم 10 بوصة (Alexa مدمجة)','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-045-W','شاشة تحكم 10 بوصة (أمبليفاير) 2 سماعة','Screens & Hubs','/img/catalog/panel-1.webp'),
  ('HS-046-W','جيتواي زيجبي 3.0 لاسلكي','Screens & Hubs','/img/catalog/panel-3.webp'),
  ('HS-047-W','جيتواي زيجبي سلكي (أبيض)','Screens & Hubs','/img/catalog/panel-3.webp'),
  ('HS-048-W','جيتواي زيجبي سلكي (دهبي)','Screens & Hubs','/img/catalog/panel-3.webp'),
  ('HS-049-W','جيتواي زيجبي سلكي (Apple HomeKit)','Screens & Hubs','/img/catalog/panel-3.webp'),
  ('HS-050-Z','مقوي إشارة زيجبي','Screens & Hubs','/img/catalog/panel-3.webp'),
  ('HS-051-W','ريموت IR ذكي بحساس حرارة ورطوبة','Remotes','/img/catalog/sensor-climate.webp'),
  ('HS-052-W','ريموت IR ذكي واي فاي','Remotes','/img/catalog/sensor-climate.webp'),
  ('HS-053-W','ريموت IR + RF ذكي واي فاي','Remotes','/img/catalog/sensor-climate.webp'),
  ('HS-054-Z','ريموت IR ذكي زيجبي','Remotes','/img/catalog/sensor-climate.webp'),
  ('HS-055-W','حساس تواجد سقف (AC 80-220V) (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-055-Z','حساس تواجد سقف (AC 80-220V) (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-056-W','حساس تواجد (DC 5V) (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-056-Z','حساس تواجد (DC 5V) (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-057-Z','حساس حركة زيجبي','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-058-W','حساس حركة واي فاي','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-059-W','حساس غاز وحرارة بشاشة','Sensors','/img/catalog/sensor-gas.webp'),
  ('HS-060-W','حساس غاز واي فاي','Sensors','/img/catalog/sensor-gas.webp'),
  ('HS-061-Z','حساس غاز زيجبي','Sensors','/img/catalog/sensor-gas.webp'),
  ('HS-062-W','حساس تسريب مياه (دائري) (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-062-Z','حساس تسريب مياه (دائري) (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-063-W','حساس تسريب مياه (بمجس) (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-063-Z','حساس تسريب مياه (بمجس) (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-064-W','محبس غاز/مياه ذكي (واي فاي)','Sensors','/img/catalog/sensor-gas.webp'),
  ('HS-064-Z','محبس غاز/مياه ذكي (زيجبي)','Sensors','/img/catalog/sensor-gas.webp'),
  ('HS-065-W','حساس دخان ذكي (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-065-Z','حساس دخان ذكي (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-066-W','حساس باب وشباك (موديل 1) (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-066-Z','حساس باب وشباك (موديل 1) (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-067-W','حساس باب وشباك (موديل 2) (واي فاي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-067-Z','حساس باب وشباك (موديل 2) (زيجبي)','Sensors','/img/catalog/sensor-climate.webp'),
  ('HS-068-W','جرس فيديو ذكي (فضي)','Intercom','/img/catalog/doorbell-1.webp'),
  ('HS-069-W','جرس فيديو ضد المياه IP65 (أسود)','Intercom','/img/catalog/doorbell-1.webp'),
  ('HS-070-W','جرس فيديو ضد المياه IP65 (أسود/أبيض)','Intercom','/img/catalog/doorbell-1.webp'),
  ('HS-071-W','جرس فيديو ذكي (أسود مربع)','Intercom','/img/catalog/doorbell-1.webp'),
  ('HS-072-W','جرس فيديو ضد المياه IP66','Intercom','/img/catalog/doorbell-1.webp'),
  ('HS-073-W','جرس فيديو ذكي (أسود/أبيض)','Intercom','/img/catalog/doorbell-1.webp'),
  ('HS-074-W','إنتركم فيديو بشاشة 4.3 بوصة','Intercom','/img/catalog/intercom-1.webp'),
  ('HS-075-W','إنتركم فيديو HD بشاشة 4.3 بوصة','Intercom','/img/catalog/intercom-1.webp'),
  ('HS-076-W','كالون ذكي أوتوماتيك LWF1','Locks','/img/catalog/lock-1.webp'),
  ('HS-077-W','كالون ذكي أوتوماتيك LWF2','Locks','/img/catalog/lock-1.webp'),
  ('HS-078-W','كالون ذكي أوتوماتيك LWF7','Locks','/img/catalog/lock-2.webp'),
  ('HS-079-W','كالون ذكي أوتوماتيك LWF9','Locks','/img/catalog/lock-2.webp'),
  ('HS-080-W','كالون ذكي أوتوماتيك LWF13','Locks','/img/catalog/lock-2.webp'),
  ('HS-081-W','كالون ذكي أوتوماتيك LWF14','Locks','/img/catalog/lock-2.webp'),
  ('HS-082-W','كالون ذكي أوتوماتيك LWF15','Locks','/img/catalog/lock-2.webp'),
  ('HS-083-W','كالون ذكي أوتوماتيك LWF17','Locks','/img/catalog/lock-2.webp'),
  ('HS-084-W','كالون ذكي أوتوماتيك LWF27','Locks','/img/catalog/lock-2.webp'),
  ('HS-085-W','كالون ذكي أوتوماتيك LWF30','Locks','/img/catalog/lock-2.webp'),
  ('HS-086-W','كالون ذكي أوتوماتيك LWF31','Locks','/img/catalog/lock-2.webp'),
  ('HS-087-W','كالون ذكي أوتوماتيك LWF33','Locks','/img/catalog/lock-2.webp'),
  ('HS-088-W','كالون ذكي أوتوماتيك LWF34','Locks','/img/catalog/lock-2.webp'),
  ('HS-089-W','كالون ذكي أوتوماتيك LWF35','Locks','/img/catalog/lock-2.webp'),
  ('HS-090-W','كالون ذكي أوتوماتيك LWF36','Locks','/img/catalog/lock-2.webp'),
  ('HS-091-W','كالون ذكي أوتوماتيك LWF37','Locks','/img/catalog/lock-2.webp'),
  ('HS-092-W','كالون ذكي أوتوماتيك LWF38','Locks','/img/catalog/lock-2.webp'),
  ('HS-093-W','كالون ذكي أوتوماتيك LWF39','Locks','/img/catalog/lock-2.webp'),
  ('HS-094-W','كالون ذكي أوتوماتيك LWF19','Locks','/img/catalog/lock-2.webp'),
  ('HS-095-W','كالون ذكي أوتوماتيك LWF22','Locks','/img/catalog/lock-2.webp'),
  ('HS-096-W','كالون ذكي نصف أوتوماتيك LWE6','Locks','/img/catalog/lock-3.webp'),
  ('HS-097-W','كالون ذكي نصف أوتوماتيك LWE9-PRO','Locks','/img/catalog/lock-3.webp'),
  ('HS-098-W','كالون ذكي نصف أوتوماتيك LWB26','Locks','/img/catalog/lock-3.webp')
) v(code, name_ar, category, image_url)
where p.code in ('JS-' || v.code, 'TS-' || v.code);
